### ISSUE TITLE
Blind Signature

### ISSUE THREAD

**Issue by preeti13456** [preeti13456/Blockchain-project#7]
How can you include a blind signature feature in the project?
Description: It is a form of digital signature in which the content of a message is disguised (blinded) before it is signed. The resulting blind signature can be publicly verified against the original, unblinded message in the manner of a regular digital signature.

Blind signatures are typically employed in privacy-related protocols where the signer and message author are different parties. Examples include cryptographic election systems and digital cash schemes.

**Comment by bijoy26** [comment]
This feature is addressed in #21

**Comment by preeti13456** [comment]
Good work you got the idea behind the implementation.
